/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const PuzzlePuzzleIdLazyImport = createFileRoute('/puzzle/$puzzleId')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const PuzzlePuzzleIdLazyRoute = PuzzlePuzzleIdLazyImport.update({
  path: '/puzzle/$puzzleId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/puzzle.$puzzleId.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/puzzle/$puzzleId': {
      id: '/puzzle/$puzzleId'
      path: '/puzzle/$puzzleId'
      fullPath: '/puzzle/$puzzleId'
      preLoaderRoute: typeof PuzzlePuzzleIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/puzzle/$puzzleId': typeof PuzzlePuzzleIdLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/puzzle/$puzzleId': typeof PuzzlePuzzleIdLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/puzzle/$puzzleId': typeof PuzzlePuzzleIdLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/puzzle/$puzzleId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/puzzle/$puzzleId'
  id: '__root__' | '/' | '/puzzle/$puzzleId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  PuzzlePuzzleIdLazyRoute: typeof PuzzlePuzzleIdLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  PuzzlePuzzleIdLazyRoute: PuzzlePuzzleIdLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/puzzle/$puzzleId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/puzzle/$puzzleId": {
      "filePath": "puzzle.$puzzleId.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
