[package]
name = "puzzlefile"
version = "0.1.0"
edition = "2021"

[dependencies]
ciborium = "0.2.2"
log = "0.4.22"
serde = { version = "1.0.210", features = ["derive"] }
thiserror = "1.0.63"
tokio = { version = "1.40.0", features = ["full"] }

[dev-dependencies]
rand = "0.8.5"
